// import type { Metadata } from "next";
// import { GeistSans } from "geist/font/sans";      // <-- THIS IS CORRECT
// import { GeistMono } from "geist/font/mono";        // <-- THIS IS CORRECT
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }



// app/layout.tsx
import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans"; // Correct import
import { GeistMono } from "geist/font/mono";   // Correct import
import "./globals.css";

// REMOVE THESE LINES:
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });
// The GeistSans and GeistMono imported above already contain the .variable property.

export const metadata: Metadata = {
  title: "Prescription Generator", // Consider updating
  description: "Generate medical prescriptions", // Consider updating
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // Use the .variable property directly from the imported GeistSans and GeistMono
    <html lang="en" className={`${GeistSans.variable} ${GeistMono.variable}`}>
      {/*
        It's common to put the font variables on the <html> tag.
        The `antialiased` class is fine on the body.
        You don't need to re-apply the .variable to the body if it's on html.
      */}
      <body className="antialiased">
        {children}
      </body>
    </html>
  );
}